name: run-and-upload-to-allure-testops

on:
  # push:
  workflow_dispatch:
    inputs:
      GITHUB_TEST_ENDPOINT:
        description: "System under test"
        required: true
        default: https://qa.testbed.url
      GITHUB_BROWSER:
        description: "Browser used for tests"
        required: true
        default: chrome
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest allure-pytest 
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://testing.allure.aws.qameta.in
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 4690
      - name: Run pytest tests
        run: |
          allurectl watch -- pytest ./test --alluredir=${ALLURE_RESULTS} --capture=no || true
          printenv | grep GITHUB_
          printenv | grep ALLURE_
        env:
          GITHUB_TEST_ENDPOINT: ${{ github.event.inputs.GITHUB_TEST_ENDPOINT }}
          GITHUB_BROWSER: ${{ github.event.inputs.GITHUB_BROWSER }}
